export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCTS',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_SELECTED_PRODUCT: 'FETCH_SELECTED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
}